name: Reusable Build Pipeline

# Define trigger on workflow call
on:
  workflow_call

# Declare environment variables
env:
  AZURE_WEBAPP_NAME: php-demo-webapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './php'      # set this to the path to your web app project, defaults to the repository root
  PHP_VERSION: '8.x'                  # set this to the PHP version to use

permissions:
  contents: read

# Declare build job steps and Github Actions ubuntu runner
jobs:
  build:
    runs-on: ubuntu-latest

# Checkout repo
    steps:
      - uses: actions/checkout@v3
# Setup PHP program using composer
      - name: Setup PHP
        uses: shivammathur/setup-php@7c0b4c8c8ebed23eca9ec2802474895d105b11bc
        with:
          php-version: ${{ env.PHP_VERSION }}

# Composer is a tool for dependency management in PHP.
# It allows you to declare the libraries your project depends on
      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@87d74d4732ddb824259d80c8a508c0124bf1c673
        with:
          files: 'composer.json'

      - name: Get Composer Cache Directory
        id: composer-cache
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

# Cache program dependencies if any to allow for faster installs in future
      - name: Set up dependency caching for faster installs
        uses: actions/cache@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

# Run composer install to install dependencies if the composer.json file exists
      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress
        
# Upload the artifact produced by composer php install
# which will be used to upload the program to Azure Web App Service
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: ./php