name: Build and deploy PHP app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  init_job:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

#Trigger build pipeline by calling the reusable workflow file
  build:
    name: "Build"
    uses: ./.github/workflows/build.yml

#Trigger deploy pipeline by calling the reusable workflow file
  deploy:
    name: "Deploy"
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit