on:
    push:
        branches: ["main"]
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: node-demo-webapp    # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
    # Run build job by calling build.yml reusable workflow file 
    build:
        uses: ./.github/workflows/build.yml
    
    # Run deploy job if build successfull
    deploy:
            runs-on: ubuntu-latest
            needs: build
            environment:
              name: 'Development'
              url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        
        
            steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: node-app
        
            - uses: azure/login@v1
              with:
                    creds: ${{ secrets.DEMO_WEBAPP_SP }}
        
            - name: 'Deploy to Azure WebApp'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
